# ============================================================
#  models.py — Core data model for predictions
# ============================================================

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone, date
from typing import Any
from enum import Enum

class PredictionType(str, Enum):
    CASHFLOW = "CASHFLOW"
    SPENDING = "SPENDING"
    BUDGET = "BUDGET"
    GOAL = "GOAL"
    SUBSCRIPTION = "SUBSCRIPTION"
    INCOME = "INCOME"
    CATEGORY = "CATEGORY"
    EMERGENCY_FUND = "EMERGENCY_FUND"

class ConfidenceLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"

class ForecastPeriod(str, Enum):
    DAYS_30 = "30_DAYS"
    DAYS_90 = "90_DAYS"
    DAYS_180 = "180_DAYS"
    DAYS_365 = "365_DAYS"

    def to_days(self) -> int:
        if self == ForecastPeriod.DAYS_30: return 30
        if self == ForecastPeriod.DAYS_90: return 90
        if self == ForecastPeriod.DAYS_180: return 180
        return 365

@dataclass
class Prediction:
    """
    A single deterministic forecast generated by the engine.
    """
    type: PredictionType
    title: str
    summary: str
    confidence: ConfidenceLevel
    methodology: str
    
    # Quantitative forecast
    forecast_value: float
    forecast_currency: str = "INR"
    
    forecast_period: ForecastPeriod = ForecastPeriod.DAYS_30
    recommendation: str | None = None
    
    prediction_date: date = field(default_factory=date.today)
    
    # Optional context (e.g. category ID, budget ID, goal ID)
    related_entity_id: str | None = None
    
    # Detailed supporting data for explanation
    metadata: dict[str, Any] = field(default_factory=dict)

    # Auto-generated
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-serialisable dictionary."""
        return {
            "id": self.id,
            "type": self.type.value,
            "title": self.title,
            "summary": self.summary,
            "confidence": self.confidence.value,
            "methodology": self.methodology,
            "forecast_value": self.forecast_value,
            "forecast_currency": self.forecast_currency,
            "forecast_period": self.forecast_period.value,
            "recommendation": self.recommendation,
            "prediction_date": self.prediction_date.isoformat(),
            "related_entity_id": self.related_entity_id,
            "metadata": self.metadata,
            "created_at": self.created_at.isoformat(),
        }

    @property
    def dedup_key(self) -> tuple[str, str, str | None]:
        """Predictions of same type and entity on same day are duplicates."""
        return (self.type.value, self.prediction_date.isoformat(), self.related_entity_id)
