"""Add UserMerchantMapping

Revision ID: 4f16331537ff
Revises: 850d780c955f
Create Date: 2026-07-19 03:45:47.280837+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers used by Alembic.
revision: str = '4f16331537ff'
down_revision: Union[str, None] = '850d780c955f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_merchant_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('raw_name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_merchant_mappings_raw_name'), 'user_merchant_mappings', ['raw_name'], unique=False)
    op.create_index(op.f('ix_user_merchant_mappings_user_id'), 'user_merchant_mappings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_merchant_mappings_user_id'), table_name='user_merchant_mappings')
    op.drop_index(op.f('ix_user_merchant_mappings_raw_name'), table_name='user_merchant_mappings')
    op.drop_table('user_merchant_mappings')
    # ### end Alembic commands ###
