"""add_confidence_score_to_transactions

Revision ID: 850d780c955f
Revises: 6abd611ade8e
Create Date: 2026-07-17 07:15:04.217889+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers used by Alembic.
revision: str = '850d780c955f'
down_revision: Union[str, None] = '6abd611ade8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('confidence_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'confidence_score')
    # ### end Alembic commands ###
