"""Add attachment_url to transactions

Revision ID: abe4a2f18302
Revises: acc0c131a38b
Create Date: 2026-07-10 11:22:37.163765+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers used by Alembic.
revision: str = 'abe4a2f18302'
down_revision: Union[str, None] = 'acc0c131a38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('attachment_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'attachment_url')
    # ### end Alembic commands ###
