# ============================================================
#  models.py — Core data model for timeline events
# ============================================================

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

from app.services.financial_timeline.enums import TimelineEventSeverity, TimelineEventType

@dataclass
class TimelineEvent:
    """
    A single chronological event generated by a timeline builder.
    """
    type: TimelineEventType
    severity: TimelineEventSeverity
    title: str
    description: str
    timestamp: datetime  # When the event occurred (e.g., transaction date)
    
    # Optional relationships
    related_transaction_ids: list[str] = field(default_factory=list)
    related_insight_ids: list[str] = field(default_factory=list)
    
    metadata: dict[str, Any] = field(default_factory=dict)

    # Auto-generated
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-serialisable dictionary."""
        return {
            "id": self.id,
            "type": self.type.value,
            "severity": self.severity.value,
            "title": self.title,
            "description": self.description,
            "timestamp": self.timestamp.isoformat(),
            "related_transaction_ids": self.related_transaction_ids,
            "related_insight_ids": self.related_insight_ids,
            "metadata": self.metadata,
            "created_at": self.created_at.isoformat(),
        }

    @property
    def dedup_key(self) -> tuple[str, str]:
        """Events of the same type happening on the same day are considered duplicates."""
        return (self.type.value, self.timestamp.date().isoformat())
